export const MESSAGE_ANALYZER_CONSTANTS = {
  URDU_SCAM_KEYWORDS: ["فوری", "رقم", "انعام", "لاٹری", "vented", "account"],
  ENGLISH_SCAM_KEYWORDS: [
    "congratulations",
    "you have won",
    "click here",
    "verify your account",
    "urgent action",
    "suspended",
    "limited time",
  ],
  URGENCY_PATTERNS: ["within 24 hours", "immediately", "last chance", "expires today"],
  AUTHORITY_KEYWORDS: ["FIA", "NADRA", "HBL", "UBL", "Jazz", "Telenor"],
  FINANCIAL_KEYWORDS: ["bank account", "credit card", "CNIC", "NTN"],
  PAKISTAN_SCAM_PATTERNS: {
    HEC_IMPERSONATION: {
      keywords: ["hec", "higher education commission"],
      scamIndicators: ["laptop", "scheme", "scholarship", "stipend", "application"],
      score: 30,
      threatType: "credential-harvesting",
      description: "HEC impersonation scam targeting students",
    },
    EASYPAISA_JAZZCASH_PRIZE: {
      platforms: ["easypaisa", "jazzcash", "sadapay", "nayapay"],
      scamIndicators: ["prize", "lottery", "won", "inam", "reward", "congratulations", "selected"],
      score: 30,
      threatType: "financial-fraud",
      description: "Mobile wallet prize/lottery scam",
    },
    SCHOLARSHIP_FEE: {
      keywords: ["scholarship", "stipend", "hec", "daeh"],
      feeIndicators: ["processing fee", "registration fee", "deposit", "advance payment", "security fee"],
      score: 25,
      threatType: "financial-fraud",
      description: "Fake scholarship requiring upfront payment",
    },
    COURIER_PAYMENT: {
      couriers: ["pakpost", "tcs", "leopards", "dhl", "m&p", "courier", "parcel"],
      scamIndicators: ["pay fee", "delivery failed", "address updated", "customs fee", "clearance"],
      score: 25,
      threatType: "financial-fraud",
      description: "Fake courier delivery payment scam",
    },
    SOCIAL_MEDIA_OTP: {
      platforms: ["instagram", "whatsapp", "facebook", "tiktok", "twitter", "snapchat"],
      scamIndicators: ["otp", "code", "verify your account", "verification", "confirm identity"],
      score: 30,
      threatType: "credential-harvesting",
      description: "Social media verification/OTP theft scam",
    },
    BANK_VERIFICATION: {
      banks: ["hbl", "alfalah", "meezan", "UBL", "MCB", "allied", "askari", "faysal", "silkbank", "bank islamic"],
      scamIndicators: ["blocked", "suspended", "verify account", "urgent", "security alert", "unauthorized"],
      score: 30,
      threatType: "phishing",
      description: "Fake bank security alert phishing scam",
    },
    JOB_OFFER: {
      keywords: ["job offer", "hiring", "salary", "employment", "vacancy", "position"],
      remoteIndicators: ["wfh", "work from home", "remote", "online job", "daily income"],
      score: 25,
      threatType: "scam",
      description: "Fake job offer scam",
    },
  },
};
